### PR TITLE
WIP: Show Required fields with an asterisk, and put a label in the header

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/openownership/data-standard/issues/144

### CODE REVIEW

**Comment by robredpath** [comment]
I think this would be appreciated in other standards, as well.

**Review by kindly — APPROVED** [review]

**Comment by robredpath** [comment]
@odscjames @kindly  is this now just the default for our docson? So, to use it elsewhere, I just need to make sure we're using this commit?

**Comment by ghost** [comment]
No. We don't really have a "default for our docson". There is a dev discussion I'm trying to start about how we handle making changes to repo's we've forked, as this is a difficult topic. Planio 19975

**Comment by robredpath** [comment]
@odscjames thanks. In that case - is it documented?  Can I read something? I'd like to get this into use on standard.threesixtygiving.org .

**Comment by ghost** [comment]
Currently, based on what we are talking about, the steps would be 

* find out what commit 360 is currently using.
* make a new branch "master-360" from that commit.
* cherry-pick the commit of this pull request to that new "master-360" branch.
* update the 360 standard to use this new "master-360" branch, and the latest commit on it.

However, we haven't fully settled on how to handle this yet so it's up in the air. (I have been pushing to discuss this because it is in effect holding up good work being done in these types of situation!) Notably, nothing in the above steps gets you to document what you've done for the benefit of future developers and the benefit of future merging-in-upstream changes. A special format of changelog is suggested in that ticket to solve that.

Ideally, I'd say please read and comment on Planio 19975 to push this forwards.

**Comment by robredpath** [comment]
[Make required fields appear with a *](https://trello.com/c/fLukq8wX/7-make-required-fields-appear-with-a)

**Pull request merged**
